// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a2206d36-0388-408f-9547-baa2f6fc85f2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onHumiWarningChange();
void onTempWarningChange();

float celTemp;
float relHumid;
bool humiWarning;
bool storageHumiStatus;
bool storageTempStatus;
bool tempWarning;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(celTemp, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(relHumid, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(humiWarning, READWRITE, ON_CHANGE, onHumiWarningChange);
  ArduinoCloud.addProperty(storageHumiStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(storageTempStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempWarning, READWRITE, ON_CHANGE, onTempWarningChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
